### ISSUE TITLE
How to uncheck checkbox?

### ISSUE THREAD

**Issue by timkley** [laracasts/Integrated#105]
I have a form that has a checkbox which is always checked on the first page load.

My controller checks if the given key is present and decides which action has to be taken.

But I found no way to uncheck a checkbox. `$this->type(false, 'checkbox')` is not working, I get the following error from `DomCrawler/Field/ChoiceFormField.php`:

```
InvalidArgumentException: Input "preview" cannot take "false" as a value (possible values: true).
```

In the `ChoiceFormField` class a `uncheck` method is present, but I found no way to trigger this from my test.

**Comment by JeffreyWay** [comment]
Fixed in recent commit.
