### ISSUE TITLE
Fatal error: Access level...

### ISSUE THREAD

**Issue by jcornil** [laracasts/Integrated#107]
1. Create a new laravel 5.1 project and add laracasts/integrated package using composer.
2. Edit tests/ExampleTest.php file as below

use Laracasts\Integrated\Extensions\Laravel as IntergrationTest;
class ExampleTest extends IntergrationTest
{
    public function testBasicExample()
    {
        $this->visit('/');
    }
}
1. run ./vendor/bin/phpunit
2. errors

Fatal error: Access level to Illuminate\Foundation\Testing\TestCase::see() must be public (as in class Laracasts\Integrated\Emulator) in /vendor/laracasts/integrated/src/Extensions/Laravel.php on line 10

**Comment by thomasneuteboom** [comment]
+1.

**Comment by GrahamCampbell** [comment]
This is an issue in laravel, not this package.

**Comment by thomasneuteboom** [comment]
The package has been partially integrated in Laravel 5.1, so that's causing the error. :)

**Comment by Zae** [comment]
so, it's not possible to use this package with L5.1 or is there something we can do to fix this? Is there another way to add this kind of easy selenium testing to laravel testing?
