### ISSUE TITLE
attachFile() calling Illuminate\Foundation\Testing\ApplicationTrait::call() incorrectly for files

### ISSUE THREAD

**Issue by Harrisonbro** [laracasts/Integrated#114]
I'm having an issue with Laravel 4.2 where the attachFile() method doesn't pass the files to the controller that's being called (when using Integrated's Laravel extension). Having walked through the code it looks like the file is being attached when `attachFile()` is being called, but the files are not then being passed to the controller. I _think_ the code path is as follows:
1. `Laracasts\Integrated\Extensions\IntegrationTrait::attachFile()` calls `Laracasts\Integrated\Extensions\IntegrationTrait::storeInput()` which attaches the file to the `Form` object.
2. When the form is submitted (using `Laracasts\Integrated\Extensions\IntegrationTrait::press('Submit')`) it calls `Laracasts\Integrated\Extensions\Traits\LaravelTestCase::submitForm()` which itself calls `...\LaravelTestCase::makeRequestUsingForm()`, which calls `...\LaravelTestCase::makeRequest()`
3. `makeRequest()` then calls `Illuminate\Foundation\Testing\ApplicationTrait::call` like so:
   
   ```
   $this->call($requestType, $uri, $parameters, $cookies, $files);
   ```
   
   But the method signature for that method (at least in my installation of Laravel 4.2) is like so:
   
   ```
   public function call($method, $uri, $parameters = [], $files = [], $server = [], $content = null, $changeHistory = true)
   ```

Note that `call()` is called with `$cookies` as the 4th parameter and `$files` as the 5th, but the method signature has `$files` as the 4th and `$server` as the 5th. If I change the way it's called to have `$files` as the 4th parameter the upload test works when using `attachFile()`.

Is this due to Integrated not supporting Laravel 4.2, or could this be fixed?

**Comment by nCrazed** [comment]
@Harrisonbro have you run into any problems caused by the argument change?

**Comment by Harrisonbro** [comment]
Sorry @nCrazed, not sure I follow — which argument change?

**Comment by nCrazed** [comment]
@Harrisonbro

> Note that call() is called with $cookies as the 4th parameter and $files as the 5th, but the method signature has $files as the 4th and $server as the 5th. If I change the way it's called to have $files as the 4th parameter the upload test works when using attachFile().

**Comment by Harrisonbro** [comment]
Ah I see, ok. To be honest it's now been so long since I was working on that test that I can't remember. I don't recall any issue with doing it that way round — the test did seem to work OK — but I subsequently abandoned the test due to this issue. I'll close this Github issue but will re-open if I run into the same thing again on a real project, and if/when that happens I'll investigate further.
