### ISSUE TITLE
How to expect "see" in a specific (HTML) element?

### ISSUE THREAD

**Issue by cve** [laracasts/Integrated#115]
Hi,

how can I test a specific element on a page e.g. 

```
<span class="price">100 $</span>
```

contains 100 $ ?

**Comment by JeffreyWay** [comment]
Can you not do:

```
$this->see('100 $');
```

**Comment by cve** [comment]
I can, but on the whole page can have a few places which has the same value (which may not be the context of that specific test) and the test result is misleading in that circumstances...

**Comment by JeffreyWay** [comment]
I don't think you can at the moment, but I'm pretty sure there's a PR here to add support for that.

**Comment by tomturton** [comment]
+1
