### ISSUE TITLE
Call to a member function enableHttpMethodParameterOverride() on a non-object

### ISSUE THREAD

**Issue by davidsoderberg** [laracasts/Integrated#13]
Hi when I Run my phpunit tests I got:
`Call to a member function enableHttpMethodParameterOverride() on a non-object in C:\Users\david\Desktop\codeblock\vendor\laracasts\integrated\src\Extens
ions\Laravel.php on line 22`

I do as your instruction in readme.md.
What do I do wrong?

**Comment by bvangraafeiland** [comment]
Is `$this->app` being set in the `TestCase` class that extends Integrated? This is a method being called on the `Request` class, through the `request` IoC binding.

Could you try to `dd($this->app)` in your `setUp` method, and see what that returns?

**Comment by davidsoderberg** [comment]
My code look like this:

```
<?php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class MenuControllerTest extends IntegrationTest {

    /** @test */
    public function it_verifies_that_pages_load_properly() {
        $this->visit('/');
    }

    /**
     * Creates the application.
     *
     * Needs to be implemented by subclasses.
     *
     * @return \Symfony\Component\HttpKernel\HttpKernelInterface
     */
    public function createApplication() {
        // TODO: Implement createApplication() method.
    }
}
```

How can I check $this->app ?

**Comment by renege** [comment]
Isn't this where Laracasts forum is for? https://laracasts.com/discuss

**Comment by bvangraafeiland** [comment]
No, this is an Integrated-related issue. What you need to do, is extend `TestCase` in `MenuControllerTest`, and extend `IntegrationTest` in `TestCase`. Right now, as you see, the `createApplication()` method is empty (and thus `$this->app` is null, hence the error), this is implemented in `TestCase`. 

This was changed in an earlier update of Integrated to allow for custom methods in the base class.

**Comment by davidsoderberg** [comment]
I have solved it with adding code below to createApplication method.

```
        $app = require __DIR__ . '/../../bootstrap/app.php';
        $app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
        return $app;
```

**Comment by bvangraafeiland** [comment]
You shouldn't do that, the `TestCase` has that code already. Like this you're gonna have to paste it in every one of your test classes.

**Comment by davidsoderberg** [comment]
I have now created a new "TestCase" for only integration testing and one for unit testing.

**Comment by DatasoftSolutionsNet** [comment]
Thanks Guys,

I beat my head on my desk for a couple hours with this issue.
Appreciate you sharing the solution.
