### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by stevedotmt** [laracasts/Integrated#20]
Is there a possibility to add the functionality to test file uploads? Testing where the file is moved to and such?

**Comment by laracasts** [comment]
Yeah - will add an "attach file" method.

**Comment by stevedotmt** [comment]
Thank you :) Keep up the awesome work!

**Comment by hardevine** [comment]
can we use any helper function to test image upload..??..any workaround..

**Comment by sahibalejandro** [comment]
I'm sure many of us are waiting for this enhancement!
Anyway, excellent work!

**Comment by JeffreyWay** [comment]
Think this should be implemented now.

5b18ce27027b1784907b780eb00c38462afd3de9

Let me know if you have any issues.

**Comment by prullenbak** [comment]
Hi,
I'm trying to use this, like this:

```
public function it_uploads_a_local_file()
{
    $this->visit('/')
        ->attachFile('photo',__DIR__.'test.jpg')
        ->press('Uploaden')->andOnPage('/meedoen');
}
```

with the test.jpg file in my /tests directory. The 'photo' file input is on my homepage. The form works in the browser, but it doesn't work in the tests. It doesn't look like it's actually submitting the file, and my validation fails because of it, because this "test" passes:

```
public function it_fails_without_a_local_file()
{
    $this->visit('/')
        ->attachFile('photo',__DIR__.'test.jpg')
        ->press('Uploaden')
        ->onPage('/')
        ->andSee('Upload a picture to continue!');
}

```

Am I doing something wrong here? I probably am :)

**Comment by hardevine** [comment]
in 
Symfony\Component\HttpFoundation\File\UploadedFile
under move method there is isValid method which needs test flag to be true as 'is_uploaded_file' [UploadedFile.php:217] gives false for non-http file transfer.

**Comment by stevedotmt** [comment]
Same here this doesn't work for me. When i use a custom request with validation it gives me the error that the file is not attached.

When I change it into a simple Request I get an exception from the move method.

I checked on browser and it work.

Tell me if you need more information to help you fix  this problem please.

Sorry for taking long to reply

**Comment by ddaveloper** [comment]
@hardevine Ok, so we now (sort of) know what the problem is...but how to fix it? Can I do that myself, or is it a bug in the package? :)

**Comment by prullenbak** [comment]
@hardevine Ok, so we now (sort of) know what the problem is...but how to fix it? Can I do that myself, or is it a bug in the package? :)

**Comment by hardevine** [comment]
@prullenbak  well, i guess, test flag is for testing UploadFile component for its own tests, maybe [vfsStream](https://github.com/mikey179/vfsStream) would work, or we could just check in Request for presence of File and not 'move' it. :)

**Comment by sahibalejandro** [comment]
This issue should be open again...

**Comment by thatdoorsajar** [comment]
I also think this should be opened again as I am having similar issues today. The `attachFile()` method returns errors exactly the same as @SteveAzz has detailed.

**Comment by stevedotmt** [comment]
Opened a new issues if you guys are interested https://github.com/laracasts/Integrated/issues/87
