### ISSUE TITLE
This is puzzling...

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#29]
I am receiving the following error when running a sample test

<pre>
Fatal error: Class IntegrateTest contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Foundation\Testing\TestCase::createApplication) in /Users/mikee/Documents/Projects/rangladex5/tests/IntegrateTest.php on line 6

Call Stack:
    0.0005     248864   1. {main}() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/phpunit:0
    0.0446    2255168   2. PHPUnit_TextUI_Command::main() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/phpunit:36
    0.0446    2255792   3. PHPUnit_TextUI_Command->run() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/TextUI/Command.php:105
    0.0623    3204536   4. PHPUnit_Runner_BaseTestRunner->getTest() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/TextUI/Command.php:127
    0.0623    3204584   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:72
    0.0629    3230448   6. PHPUnit_Runner_StandardTestSuiteLoader->load() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:127
    0.0631    3263912   7. PHPUnit_Util_Fileloader::checkAndLoad() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:43
    0.0631    3264048   8. PHPUnit_Util_Fileloader::load() /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
    0.0632    3268088   9. include_once('/Users/mikee/Documents/Projects/rangladex5/tests/IntegrateTest.php') /Users/mikee/Documents/Projects/rangladex5/vendor/phpunit/phpunit/src/Util/Fileloader.php:58

</pre>

Here is the test

<pre>

<?php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class IntegrateTest extends IntegrationTest {

    /** @test  */
    public function it_should_visit_home()
    {
        $this->visit('/');
    }

}

</pre>

**Comment by mikeerickson** [comment]
Not sure why that got hammered

<?php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class IntegrateTest extends IntegrationTest {

```
/** @test  */
public function it_should_visit_home()
{
    $this->visit('/');
}
```

}

**Comment by bvangraafeiland** [comment]
As the readme mentions, your base `TestCase` should extend `IntegrationTest`. The actual test classes extend `TestCase`.

**Comment by mikeerickson** [comment]
@bastiaan89 Ah Michael, come on now!   I _knew_ that but completely let it slip my mind.  Thanks for pointing me in the right direction.
