### ISSUE TITLE
Interface Methods

### ISSUE THREAD

**Issue by slakbal** [laracasts/Integrated#3]
Hi,

When I do the following:

```
use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class ExampleTest extends IntegrationTest {}
```

It wants me to implement the following methods: follow, check, tick, select, dump

Is that correct? or should one just ignore them?

Thanks!

**Comment by laracasts** [comment]
All those methods are stored in a trait that the Laravel class includes. So the interface has been satisfied.

Are you referring to an editor notification or something?

**Comment by slakbal** [comment]
Yeah, phpstorm was notifying on them.

Thanks got the package running and works like a charm! Enjoying it!

Good Stuff!
