### ISSUE TITLE
DatabaseTransactions not using correct .env file

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#33]
When using DatabaseTransactions trait, it is using the .env file regardless of the existence of .env.testing, thus all tests are actually using the production database.

Surely I can change the value in .env during testing, but that would defeat the purpose.

Here is a screenshot of the execution, echoing the environment value

http://d.pr/i/1eCpx

**Comment by JeffreyWay** [comment]
Are you using L4 or L5?

**Comment by mikeerickson** [comment]
L5

**Comment by ziming** [comment]
@JeffreyWay Does being on L4 matters for this package?

**Comment by JeffreyWay** [comment]
Laravel 5 doesn't look for a `.env.testing` file when running PHPUnit. So neither does this package. 

Declare your testing env vars in `phpunit.xml`.
