### ISSUE TITLE
Receiving error when returning a 404 page w/ JSON result

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#38]
I have a response of

<code>

{"error":{"message":"Resource Not Found","status_code":404}}

</code>

which produces the following error

<code>

Time: 5.05 seconds, Memory: 20.75Mb

There was 1 error:

1) BatterTest::it_should_show_return_error_on_bad_request
InvalidArgumentException: The current node list is empty.

/home/vagrant/code/rangladex5/vendor/symfony/dom-crawler/Symfony/Component/DomCrawler/Crawler.php:580
/home/vagrant/code/rangladex5/vendor/laracasts/integrated/src/Extensions/Laravel.php:152
/home/vagrant/code/rangladex5/vendor/laracasts/integrated/src/Extensions/IntegrationTrait.php:365
/home/vagrant/code/rangladex5/vendor/laracasts/integrated/src/Extensions/Laravel.php:65
/home/vagrant/code/rangladex5/vendor/laracasts/integrated/src/Extensions/IntegrationTrait.php:74
/home/vagrant/code/rangladex5/tests/functional/battertest.php:38

</code>

**Comment by JeffreyWay** [comment]
I need more information here. 

Show me your test method, and the route that returns that response.

**Comment by mikeerickson** [comment]
@JeffreyWay 

Here is the test

```
/** @test */
public function it_should_show_return_error_on_bad_request()
{
    $this->visit("batters/55555")->dump();
         // ->see('Resource Not Found');
}
```

Simple Route Resource

Route::resource('test','TestController');

and the controller 'show' method

```
public function show($id)
{
    $batter = Batter::find($id);
    return ( ! $batter ) ? $this->respondNotFound() : $this->fractal->item($batter, $this->transformer);
}


protected function respondNotFound($statusCode = 404, $message = 'Resource Not Found')
{
    return Response::json([
            'error' => [
                'message' => $message,
                'status_code' => $statusCode
            ]
        ], $statusCode);
}
```

**Comment by JeffreyWay** [comment]
The `visit` method is to simulate visiting a page in the browser. So, as part of that call, it runs an assertion to ensure that a 200 response is returned.

For an API, right now, use `$this->call('GET', 'json/end-point')` - assuming you're using the Laravel extension.

``` php
/** @test */
public function it_does_something()
{
    $this->call('GET', '/json-endpoint');

    $this->assertEquals(404, $this->statusCode());
}
```

I'll have a think on this. Maybe we can add something to simplify/clarify this, because I agree that it could be confusing. I wonder what a good method for API requests could be.

Just brainstorming...

```
$this->hit('/json-endpoint');
$this->api('/json-endpoint');
$this->apiRequest('/json-endpoint');
$this->makeApiRequest('/json-endpoint');
$this->request('/json-endpoint')->andSeeStatusCode(404);
```

Anything better?

**Comment by mikeerickson** [comment]
Ah, I see what you are saying.  My test is (properly) failing because the response code is not 200.

That makes good sense and selenium test might not be the best tool to perform an API test (I have used integrated Laravel already to test all end points) 

Regarding other topic of possible API, I am thinking 

$this->send(method, uri)->isJSON()->shouldReturn(404)

**Comment by mikeerickson** [comment]
Or you can have separate methods for each type of request 

$this->get(uri)
$this->post(uri, data)
$this->put()
$this->patch()
$this->delete()

$this->isJSON() // would be nice 

And, after thinking this through, really makes it clear using selenium to test API is wrong solution.

Having said that, the above routines would sure be nice for testing APIs :)

**Comment by JeffreyWay** [comment]
Okay - I've pushed a first draft to dev-master.

https://github.com/laracasts/Integrated/commit/5dcc7b5df56e61c1902ef8702c2edd59cf447f27

Use like so:

``` php
 /** @test */
 public function it_makes_api_requests()
 {
     $this->get('/json-endpoint')
          ->seeJson()
          ->seeStatusCode(200)
          ->seeJsonEquals(['name' => 'joe', 'age' => 30])
          ->seeJsonContains(['name' => 'joe']);
 }
```

**Comment by mikeerickson** [comment]
Perfect!  I will have a look in the morning...

Go to sleep :)

**Comment by danwall** [comment]
How about a seeContentType() so we can ensure that we're getting `application/json` or `application/atom+xml` for feeds?

**Comment by mikeerickson** [comment]
@JeffreyWay Thanks for adding the above methods!  All is working great!  Now just need to figure out why Selenium is not hitting URL .

**Comment by JeffreyWay** [comment]
@danwall - Yeah, we could add that.
