### ISSUE TITLE
Latest update with ->seeJsonContains not completely right

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#39]
Using this test

```
/** @test */
 public function it_makes_api_requests()
 {
     $this->get("fractal/{$this->batterID}")
          ->seeJson()
          ->seeStatusCode(200)
          ->dump()
          ->seeJsonContains(['name' => 'Trout, Mike', 'HR' => '37']);
 }
```

I receive these results (using dump() routine)

...string(142) "{"id":1318,"team":"LAA","name":"Trout, Mike","AB":602,"H":173,"2B":39,"3B":0,"HR":36,"RBI":111,"BB":83,"AVG":".287","OBP":".368","SLG":".561"}"

The 'seeJsonContains' routine is testing HR => 37 but data is actually 36 and the test passes

**Comment by JeffreyWay** [comment]
`dump()` dies. Remove that and try again?

**Comment by mikeerickson** [comment]
No, I was just using dump to see the data.  When removed, the test passes.

**Comment by mikeerickson** [comment]
@jeffrey_way this issue is still open.  The test is passing when in fact it should be failing
