### ISSUE TITLE
Laravel exntesion not working

### ISSUE THREAD

**Issue by dorvidas** [laracasts/Integrated#47]
Followed installation instruction. Trying to use code below:
<?php // tests/TestCase.php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class TestCase extends IntegrationTest {
    // ...
}

Getting error:
Fatal error: Class TestCase contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Foundation\Testing\TestCase:
laravel-dmca\tests\ExampleTest.php on line 5

Call Stack:
    0.0010     236024   1. {main}() D:\www\laravel-dmca\vendor\phpunit\phpunit\phpunit:0
    0.0270    1729736   2. PHPUnit_TextUI_Command::main() D:\www\laravel-dmca\vendor\phpunit\phpunit\phpunit:36
    0.0270    1736336   3. PHPUnit_TextUI_Command->run() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\TextUI\Command.php:105
    0.0270    1739000   4. PHPUnit_TextUI_Command->handleArguments() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\TextUI\Command.php:115
    0.0370    2348672   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\TextUI\Command.php:670
    0.0370    2349920   6. PHPUnit_Util_Configuration->getTestSuite() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Util\Configuration.php:853
    0.0530    2587904   7. PHPUnit_Framework_TestSuite->addTestFiles() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Util\Configuration.php:940
    0.0530    2588728   8. PHPUnit_Framework_TestSuite->addTestFile() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Framework\TestSuite.php:405
    0.0530    2620840   9. PHPUnit_Util_Fileloader::checkAndLoad() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Framework\TestSuite.php:333
    0.0540    2620968  10. PHPUnit_Util_Fileloader::load() D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Util\Fileloader.php:42
    0.0550    2623448  11. include_once('D:\www\laravel-dmca\tests\ExampleTest.php') D:\www\laravel-dmca\vendor\phpunit\phpunit\src\Util\Fileloader.php:58

Goutte extension seems working...

**Comment by JeffreyWay** [comment]
You didn't show what ExampleTest looks like.

**Comment by mattclements** [comment]
TestCase.php

``` php
<?php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class TestCase extends IntegrationTest {
    // ...
}
```

MyTest.php

``` php
<?php

use Laracasts\Integrated\Extensions\Laravel as IntegrationTest;

class MyTest extends IntegrationTest
{
    private $_ok_data = [

    ];

    /** @test */
    public function testApiReturnsJson()
    {
        $this->post('/api/v1/test', $this->_ok_data)
            ->seeJson();
    }

    /** @test */
    public function testApiReturnsOk()
    {
        $this->post('/api/v1/test', $this->_ok_data)
            ->seeStatusCode(200);
    }
}
```

I am getting the same error too:

```
PHP Fatal error:  Class MyTest contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Foundation\Testing\TestCase::createApplication) in /Users/matt/Projects/blah/tests/MyTest.php on line 6
```

Probably something stupid I know!

**Comment by JeffreyWay** [comment]
@mattclements - Your TestCase class is extending the Laravel extension. So just have MyTest extend TestCase.

**Comment by mattclements** [comment]
Thanks @JeffreyWay !!!
