### ISSUE TITLE
Fatal error using Integrated w/ --testdox flag

### ISSUE THREAD

**Issue by mikeerickson** [laracasts/Integrated#50]
Using Integrated with PHPUnit --testdox attribute throws following error

$ phpunit --testdox tests

`
Fatal error: Cannot use object of type Laracasts\Integrated\AnnotationReader as array in /Users/mikee/Documents/Projects/api-lumen/vendor/phpunit/phpunit/src/Util/TestDox/ResultPrinter.php on line 234
`

**Comment by JeffreyWay** [comment]
Hmm - I've tried, but can't reproduce.

http://d.pr/i/c7ub

I'd need more information.

**Comment by JeffreyWay** [comment]
Hmm - honestly have no idea why this is happening.

If someone digs in and finds out why, please submit a PR.

**Comment by mikeerickson** [comment]
Hey Jeff

I will have a closer look at this and see if I can track down the issue.
