### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by mattclements** [laracasts/Integrated#52]
Hi @JeffreyWay - Thanks for the package - loving converting our existing tests over to the package!

Is there anyway to test an API via Basic Auth for a Laravel Project; I originally thought about settings a baseURL to include the User/Pass, however this doesn't seem to have worked.

I also need to set the `Content-Type` and `Accepts` header when making the request.

If not I can just use `curl` requests to test as we currently do - just trying to see if I can unify everything

**Comment by Flambe** [comment]
``` php
$this->withHeaders();
```

was [recently added](https://github.com/laracasts/Integrated/wiki/Testing-APIs#withheadersarray-headers) which'll allow you to add the headers in.

If you're using an authorization header for Basic auth, you should be able to send that through `withHeaders()` as well.

**Comment by mattclements** [comment]
Perfect thanks!
