### ISSUE TITLE
seeJsonContains fails on partial matches

### ISSUE THREAD

**Issue by vjandrea** [laracasts/Integrated#54]
``` php
class ApiTest extends TestCase {
    public function test_users_index()
    {
        $this->get('api/users')->seeJsonContains(['id' => "1"]);
    }
```

fails with this error:

```
1) ApiTest::test_users_index
Dang! Expected {"id":"1"} to exist in [{"id":"1","username":"root","email":"root@<snip>
```

The same happens if i look for "id" => 1 (with the value expressed as integer).
I don't know what i'm doing wrong here, maybe it's a bug?

**Comment by mikeerickson** [comment]
Seems your result is an array (of json) so it is not finding it.  In your code that returns the json result, make sure it returns a single object. 

Otherwise you will need to use -> see(...)

**Comment by Flambe** [comment]
@mikeerickson From the looks of the route name 'users', it's suppose to return an array of users, so the array of objects can't be avoided.

Also looking at the [Testing APIs (5:10ish)](https://laracasts.com/series/intuitive-integration-testing/episodes/6) cast jeff did, jeff is also using an array of objects with the seeJsonContains function. So I think @vjandrea has the correct syntax & data.

**Comment by vjandrea** [comment]
@mikeerickson I can't use `see()` because i'm looking for json, not for text. `see()` expects a string, not an array as parameter. The only way to use `see()` is to search for a particular string like

``` php
$this->get('api/users')->see('{"id":"1"');
```

Notice the missing closing bracket, if i add it it won't find anything. It's a bad workaround.

@Flambe exactly, i'm looking for a particular id among a collection, and looking at ApiRequest.php source that's what's it's supposed to do. Another test fails in the same way when i'm fetching a single item:

``` php
    public function test_users_show()
    {
        $random_id = rand(1,10);

        $this->get('api/users/' . $random_id)
            ->seeJsonContains(['id' => "{$random_id}"]);
    }
```

fails with:

```
5) ApiTest::test_users_show
Dang! Expected {"id":"4"} to exist in {"id":"4","username":"registered","email":"registered@
```

I casted `$random_id` as a string because otherwise the result would be:

```
Dang! Expected {"id":4} to exist in {"id":"4","username":"registered","email":"registered
```

Since the raw json contains integers encoded as strings i feared it was a type mismatch problem.

**Comment by JeffreyWay** [comment]
This should be fixed now. Please update, and let me know if it's still failing on your end.

**Comment by vjandrea** [comment]
[EDIT] I can confirm that everything works now. I cleaned up all workaround methods and now it works smoothly.

**Comment by vjandrea** [comment]
Unfortunately with the latest version `(dev-master 4f4eed7)` i had again the same issues but i discovered that now there's a stricter type comparison. My failing tests became again green when i forced the ids to be casted to integers, adding

``` php
protected $casts = ['id' => 'integer'];
```

to my models.

**Comment by BrianDillingham** [comment]
I noticed this as well so I just checked {"id":"4"} instead of {"id":4} but did also notice that it doesn’t register as an assertion when it passes, I force failed it and it fails but does not assert. 

OK (2 tests, 1 assertion)
