### ISSUE TITLE
Add Negative Versions for Verification Tests

### ISSUE THREAD

**Issue by EdRands** [laracasts/Integrated#56]
First off, loving this package! Because of it, I'm actually writing tests for a project for the first time. Sometimes I run my tests just to see the beautiful green, even though no code changed.

In one of my tests, I'd like to verify that a string is _not_ on the page. It would be handy to do this:

``` PHP
$this->visit('/')
     ->andNotSee("It's the end of the world as we know it!")
```

PHPUnit has an assertNot for pretty much everything. While not relevant for action oriented tests, it would be helpful if I could be so for the verification tests like see(), seeFile(), seeInDatabase(), seePageIs() and anywhere else it seems logical to have a negative counterpart.

Although in most cases, "not" doesn't seem to be the most natural sounding word choice, especially without the "and" prefix. Maybe there's a better one.

**Comment by JeffreyWay** [comment]
Yep - planning on this.
