### ISSUE TITLE
Struggling with `seeJsonContains` to test imbricated arrays

### ISSUE THREAD

**Issue by antoinerey** [laracasts/Integrated#58]
Hello,

I can't get `seeJsonContains($array)` working properly with imbricated jsons.

I'm returning from my controller this array :

``` php
$array = 
[
    'user' => [
      'email' => $email
    ]
]
```

So it's converted by the `response()->json($array)` to :

``` json
{
    "user": {
        "email": "john@local.host"
    }
}
```

But whenever I call :

``` php
$this->seeJsonContains([
    'user' => [
         'email' => 'john@local.host' 
    ]
]);
```

**My test fails.**

Any idea ?

**Comment by JeffreyWay** [comment]
What does the test failure show in the terminal? Does it work if you use `seeJsonEquals`?

**Comment by antoinerey** [comment]
I messed up with my previous message. I'm not only returning the username, but the full user instead.

Just to be clear :

I am testing the register for users.

So, I create a user in database using Eloquent, and return the result. As below :

``` php
$user = User::create([
    'email' => 'test@local.host',
    'password' => 'password'
]);

$data = [
    'user' => $user,
    'other' => $stuff
];

return new JsonResponse($data, 201);
```

And I'm testing this with :

``` php

$url = 'api/v1/users';

$data = [
   'email' => 'john@doe.com',
   'password' => 'password'
];

$expectedJson = [
    'user' => [
        'email' => 'john@doe.com,
    ]
];

$this->post($url, $data)
    ->seeJsonContains($expectedJson)
    ->seeStatusCodeIs(201);
```

So, I tried with `seeJsonEquals($array)`. That's the same result :

```
Dang! Expected {"user":{"email":"john@doe.com"}} to exist in {"user":{"email":"john@doe.com","updated_at":"2015-04-25 17:10:05","created_at":"2015-04-25 17:10:05","id":13},"token":"xxx"}, but nope. Ideas?
```

**Comment by JeffreyWay** [comment]
Hmm, this might be expected behavior. You expect the response to contain the given JSON, which is basically `['user' => ['email' => 'john@doe.com']]`, but it doesn't. It contains more than that in the `user` array. So it fails. You could do:

```
$this->post($url, $data)->andSeeJsonContains(['email' => 'john@doe.com']);
```
