### ISSUE TITLE
Creating additional functions

### ISSUE THREAD

**Issue by bvangraafeiland** [laracasts/Integrated#6]
As of now, am I correct in assuming that the only way to add your own functions to the integration tests (such as `dontSeeInDatabase()`) is to have another base class (e.g. `IntegrationTestCase`) extending the Integrated `Laravel` class, and define the methods on there? It then becomes

`TestCase > Integrated\Laravel > IntegrationTestCase`

I can't place any helpers on `TestCase` because it's the superclass.

**Comment by JeffreyWay** [comment]
Yeah, I've been thinking about this, too. A few ways we could handle it. Will be toying around with it today. In the meantime...

Things like `dontSeeInDatabase` can be added to the API. That makes sense to me.

And, of course, you could use a trait.

**Comment by JeffreyWay** [comment]
Okay, fixed.

69064f2e77da1173657e7bf75a673ac182591768

Have your TestCase class extend `Laracasts\Integrated\Extensions\Laravel` now.
