### ISSUE TITLE
Call to a member function on null

### ISSUE THREAD

**Issue by EdRands** [laracasts/Integrated#60]
This is my test, which worked perfectly fine on version 0.14, but breaks after updating to 0.15

I'm getting:
`PHP Fatal error:  Call to a member function type() on null in ContactPageTest.php on line 17`

This is the code it triggers on:

``` PHP
    /**
     * @test
     */
    public function userCanMakeContact() {
        $this->visit('/')
            ->click('Contact Ed')
            ->see('Contact Ed, Your Computer Guy')
            ->onPage('/contact')
            ->type($this->validName, '#contactName') # Line 17
            ->type($this->validEmail, '#contactEmail')
            ->type($this->validPhone, '#contactPhone')
            ->type($this->validMessage, '#contactMessage')
            ->press('Send')
            ->see(Lang::get('contact.success'))
    }
```

I presume this means onPage() isn't returning $this as an object.

You know, a set of tests for this package would help prevent these problems after a major refactor. :wink: I'd create some, but I'm concerned at my novice level I wouldn't do a decent job.

**Comment by JeffreyWay** [comment]
There's a full test app already. I'll put it up on GitHub.

Fixed.
