### ISSUE TITLE
submitForm(): _token is saved with all other fields

### ISSUE THREAD

**Issue by pvledoux** [laracasts/Integrated#66]
Hi,

I have a problem with the following test:

```
$newCategory = [
    'name'      => 'TEST',
    'group_id'  => 1,
    'parent_id' => null
];

$this->visit('/categories/create')
    ->submitForm('Save', $newCategory)
    ->verifyInDatabase('categories', ['name' => 'TEST']);
```

I get the following error:

```
SQLSTATE[HY000]: General error: 1 table categories has no column named _token
```

Here is the code of my store method:

```
public function store(CategoryRequest $request)
{
    $category = new Category;
    $category->fill($request->all());
    $category->save();
}
```

I'm bypassing the Csrf check directly in the middleware when env is testing, so it is supposed to not use that field, but it is submitted and save() is trying to store it in the DB.

How can I avoid that?

Pv

**Comment by JeffreyWay** [comment]
Set your fillable fields on the Category model.

This isn't a bug with the Integrated package.

**Comment by pvledoux** [comment]
Weird fillable is set:

```
protected $fillable = ['name', 'label', 'group_id', 'parent_id'];
```

I will dig a bit deeper tomorrow.

Cheers,

Pv
