### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Butochnikov** [laracasts/Integrated#7]
Laravel 4.2

`composer require laracasts/integrated --dev`

Result:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laracasts/integrated 0.10.1
    - Installation request for laracasts/integrated 0.10.* -> satisfiable by laracasts/integrated[0.10.0, 0.10.1].
    - Conclusion: remove symfony/dom-crawler v2.5.10
    - laracasts/integrated 0.10.0 requires symfony/dom-crawler ~2.6 -> satisfiable by symfony/dom-crawler[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5].
    - Can only install one of: symfony/dom-crawler[v2.6.0, v2.5.10].
    - Can only install one of: symfony/dom-crawler[v2.6.1, v2.5.10].
    - Can only install one of: symfony/dom-crawler[v2.6.2, v2.5.10].
    - Can only install one of: symfony/dom-crawler[v2.6.3, v2.5.10].
    - Can only install one of: symfony/dom-crawler[v2.6.4, v2.5.10].
    - Can only install one of: symfony/dom-crawler[v2.6.5, v2.5.10].
    - Installation request for symfony/dom-crawler == 2.5.10.0 -> satisfiable by symfony/dom-crawler[v2.5.10].
```

**Comment by JeffreyWay** [comment]
Hmm - just ran that command with a fresh install of Laravel, and everything worked great.

Are you pulling in any other test packages through Composer that might cause this?

(Closing, but feel free to respond.)

**Comment by Butochnikov** [comment]
Just tried fresh install Laravel:
1. `composer create-project laravel/laravel . 4.2 --prefer-dist`
   ОК
2. `composer require laracasts/integrated --dev` 
   ERROR

```
Using version 0.11.* for laracasts/integrated                                                                                                                  
./composer.json has been updated                                                                                                                               
Loading composer repositories with package information                                                                                                         
Updating dependencies (including require-dev)                                                                                                                  
Your requirements could not be resolved to an installable set of packages.                                                                                     

  Problem 1                                                                                                                                                    
    - Installation request for laracasts/integrated 0.11.* -> satisfiable by laracasts/integrated[0.11.0].                                                     
    - Conclusion: remove symfony/dom-crawler v2.5.10                                                                                                           
    - laracasts/integrated 0.11.0 requires symfony/dom-crawler ~2.6 -> satisfiable by symfony/dom-crawler[v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5].     
    - Can only install one of: symfony/dom-crawler[v2.6.0, v2.5.10].                                                                                           
    - Can only install one of: symfony/dom-crawler[v2.6.1, v2.5.10].                                                                                           
    - Can only install one of: symfony/dom-crawler[v2.6.2, v2.5.10].                                                                                           
    - Can only install one of: symfony/dom-crawler[v2.6.3, v2.5.10].                                                                                           
    - Can only install one of: symfony/dom-crawler[v2.6.4, v2.5.10].                                                                                           
    - Can only install one of: symfony/dom-crawler[v2.6.5, v2.5.10].                                                                                           
    - Installation request for symfony/dom-crawler == 2.5.10.0 -> satisfiable by symfony/dom-crawler[v2.5.10].                                                 


Installation failed, reverting ./composer.json to its original content.                                                                                        
```

**Comment by Butochnikov** [comment]
https://github.com/laracasts/Integrated/commit/e22ed654a3dfecb2c39b3ae5daeeb5512fa9330a
this change is not helped

What could be the solution?

**Comment by tienkhoi** [comment]
Samething happened with me for Laravel 4.1

Using version ^0.15.5 for laracasts/integrated
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laracasts/integrated ^0.15.5 -> satisfiable by laracasts/integrated[0.15.5].
    - Conclusion: remove symfony/dom-crawler v2.4.10
    - Conclusion: don't install symfony/dom-crawler v2.4.10
    - laracasts/integrated 0.15.5 requires symfony/dom-crawler ~2.5|~2.6 -> satisfiable by symfony/dom-crawler[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6
.6, v2.6.7].
    - Can only install one of: symfony/dom-crawler[v2.5.0, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.1, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.10, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.11, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.2, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.3, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.4, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.5, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.6, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.7, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.8, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.5.9, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.0, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.1, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.2, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.3, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.4, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.5, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.6, v2.4.10].
    - Can only install one of: symfony/dom-crawler[v2.6.7, v2.4.10].
    - Installation request for symfony/dom-crawler == 2.4.10.0 -> satisfiable by symfony/dom-crawler[v2.4.10].

**Comment by atharnaeem** [comment]
Problem 1
    - instaclick/php-webdriver 1.4.3 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - instaclick/php-webdriver 1.4.2 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - instaclick/php-webdriver 1.4.1 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - instaclick/php-webdriver 1.4.0 requires ext-curl \* -> the requested PHP extension curl is missing from your system.
    - laracasts/integrated 0.15.6 requires instaclick/php-webdriver ~1.4 -> satisfiable by instaclick/php-webdriver[1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Installation request for laracasts/integrated ^0.15.6 -> satisfiable by laracasts/integrated[0.15.6].
Installation failed, reverting ./composer.json to its original content.

but on the same virutal machine when i execute curl --verison it gives me the following result

curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

It says curl is installed, Please Help

**Comment by tam5** [comment]
I am trying to install with a fresh installation of Laravel 5.2.22.

I run `composer require laracasts/integrated --dev` and I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laracasts/integrated ^0.15.6 -> satisfiable by laracasts/integrated[0.15.6].
    - Conclusion: remove symfony/css-selector v3.0.3
    - Conclusion: don't install symfony/css-selector v3.0.3
    - laracasts/integrated 0.15.6 requires symfony/css-selector ~2.5|~2.6 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.2, v2.8.3].
    - Can only install one of: symfony/css-selector[v2.8.0, v3.0.3].
    - Can only install one of: symfony/css-selector[v2.8.1, v3.0.3].
    - Can only install one of: symfony/css-selector[v2.8.2, v3.0.3].
    - Can only install one of: symfony/css-selector[v2.8.3, v3.0.3].
    - Installation request for symfony/css-selector == 3.0.3.0 -> satisfiable by symfony/css-selector[v3.0.3].


Installation failed, reverting ./composer.json to its original content.
```

What do I need to do?

**Comment by mr-Sepi0l** [comment]
Get exactly the same error with css-selector. What should i do for it ?

**Comment by deleugpn** [comment]
I just got this with Laravel 5.2 and Dingo API

```
   "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "dingo/api": "1.0.*@dev",
        "tymon/jwt-auth": "0.5.*",
        "prettus/l5-repository": "^2.5",
        "michelf/php-markdown": "^1.6",
        "barryvdh/laravel-cors": "^0.8.0",
        "laravel/socialite": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*"
    },
```

and the error message

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laracasts/integrated ^0.15.6 -> satisfiable by laracasts/integrated[0.15.6].
    - Conclusion: remove symfony/css-selector v3.0.4
    - Conclusion: don't install symfony/css-selector v3.0.4
    - laracasts/integrated 0.15.6 requires symfony/css-selector ~2.5|~2.6 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6].
    - Can only install one of: symfony/css-selector[v2.8.0, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.1, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.2, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.3, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.4, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.5, v3.0.4].
    - Can only install one of: symfony/css-selector[v2.8.6, v3.0.4].
    - Installation request for symfony/css-selector (locked at v3.0.4, required as 2.8.*|3.0.*) -> satisfiable by symfony/css-selector[v3.0.4].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by deleugpn** [comment]
I ended up changing my composer.json to this

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "dingo/api": "1.0.*@dev",
        "tymon/jwt-auth": "0.5.*",
        "prettus/l5-repository": "^2.5",
        "michelf/php-markdown": "^1.6",
        "barryvdh/laravel-cors": "^0.8.0",
        "guzzlehttp/guzzle": "~5.3",       <--- Make sure to pull 5.3 instead of 6
        "laravel/socialite": "^2.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*",       <--- Only 2.8
        "symfony/dom-crawler": "2.8.*"       <--- Only 2.8
    },
```

I had **symfony/[css|doom]** as 3.0, which caused the error previously published.
After that, I got an error at GuzzleHTTP 6.2 pulled by **laravel/socialite** so I forced the use of **~5.3** to be able to successfully install **Integrated**.

**Comment by vernard** [comment]
@Deleugpn Thanks. Your solution helped me.

**Comment by dhirajpatra** [comment]
You need to install 
```
 "require-dev": {
        "fzaninotto/faker": "~1.4",
        "laracasts/integrated": "^0.15.6",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "symfony/css-selector": "2.8.*",
        "symfony/dom-crawler": "2.6.*"
    },
``` 
See above I have added following two lines in composer.json

"symfony/css-selector": "2.8.*",
"symfony/dom-crawler": "2.6.*"


and run : composer update
then run : composer require laracasts/integrated --dev

It will fix the error.

**Comment by renatoagomes** [comment]
@dhirajpatra solution worked for me. Nice work bro :+1:

**Comment by dhirajpatra** [comment]
Thank you.

**Comment by soanarin** [comment]
I have managed to resolve it this way: first run this
`composer require --dev symfony/css-selector:~2.7`
and then
`composer require laracasts/integrated --dev`
and it works.

**Comment by luyandasiko** [comment]
Just gone through this very same issue with 5.4 and I have tried all the suggestions made above but the dependencies keep on cascading down through other packages.

```
 Problem 1
    - fabpot/goutte v2.0.4 requires guzzlehttp/guzzle >=4,<6 -> no matching package found.
    - fabpot/goutte v2.0.3 requires guzzlehttp/guzzle >=4,<6 -> no matching package found.
    - fabpot/goutte v2.0.2 requires guzzlehttp/guzzle 4.* -> no matching package found.
    - fabpot/goutte v2.0.1 requires guzzlehttp/guzzle 4.* -> no matching package found.
    - fabpot/goutte v2.0.0 requires guzzlehttp/guzzle 4.* -> no matching package found.
    - laracasts/integrated 0.15.6 requires fabpot/goutte ~2.0 -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - Installation request for laracasts/integrated ^0.15.6 -> satisfiable by laracasts/integrated[0.15.6].
```

Changing Guzzle back to `~5.3` breaks the Constant Contact PHPSdk... :-(`
