### ISSUE TITLE
seeJsonContains() does not return reference to object anymore

### ISSUE THREAD

**Issue by kant312** [laracasts/Integrated#74]
Hi Jeffrey,

I found that on version 0.15.4 of Integrated, the "seeJsonContains()" method was refactored and does not return the reference to the object anymore:
https://github.com/laracasts/Integrated/blob/0.15.4/src/Extensions/Traits/ApiRequests.php#L182

The problem is that it breaks some tests which were relying on chain method calling. It's no big deal though, but I think that the problem should be fixed by simply returning $this at the end of the method.

Thanks for the module btw!

**Comment by JeffreyWay** [comment]
Thx!
