### ISSUE TITLE
How do I delete/clear a text input

### ISSUE THREAD

**Issue by sameerpanjwani** [laracasts/Integrated#76]
I am trying to run a couple of Selenium tests and want to use the same session for all the tests to save time from opening a browser each time. However, I am not able to find a way to clear the text inputs that I am filling. 

Example code:

$this->visit('login')
            ->see('Login')
            ->type('abc!@!', 'email')
            ->press('Login')
            ->see('Please enter a valid email');

$this->type('valid@email.com')->press('Login')->see('Success');

However, this just appends to the previous input.

Essentially is there an equivalent command of sendKeys or like pressing "Delete" / "Backspace" on the input. The example above might not really reflect why I want to do "delete" but there are certain js outputs that I need to confirm only on a "Delete"/"Backspace" of an input.

**Comment by BrianDillingham** [comment]
It failing should be one test and it passing should be another

**Comment by BrianDillingham** [comment]
@sameerpanjwani they should be separate tests

```php
public function test_should_fail_with_invalid_email()
{
    $this->visit('login')
         ->type('abc!@!', '#email')
         ->press('Login')
         ->see('Please enter a valid email');
}

public function test_should_accept_valid_email()
{
    $this->visit('login')
         ->type('valid@email.com', '#email')
         ->press('Login')
         ->see('Success');
}
```

PS: Github issues are better suited for bugs vs support, checkout Stackoverflow
http://stackoverflow.com/questions/tagged/laravel

**Comment by bobbybouwmann** [comment]
You will have to use basic selenium calls to do so 

http://geekpad.ca/blog/post/automating-browser-testing-with-phpunit-and-selenium
