### ISSUE TITLE
Input::all()

### ISSUE THREAD

**Issue by davidsoderberg** [laracasts/Integrated#79]
Hi, when I use the facade `Input::all()` it gives `[]`, but when I use `Input::get('field')` it works...
Why?

**Comment by bobbybouwmann** [comment]
How is this effecting your tests? Is this even related to the integrated package?

**Comment by davidsoderberg** [comment]
I cant get the user input. Yes this problem only exists with this package :(

**Comment by JeffreyWay** [comment]
Hmm - if someone else has encountered the same issue, please leave a comment here to let me know.

**Comment by yajra** [comment]
@JeffreyWay I used to have this same issue on my [datatables](https://github.com/yajra/laravel-datatables) package but what I use is `Request::capture()` instead. But when I refactor the package and enabled IOC/dependency injection, it works. Though it's weird why `laracasts\integrated` does not read the input on `Request::capture()`
