### ISSUE TITLE
Only accepts <input type="submit"> for formSubmit() and press() - limits usage

### ISSUE THREAD

**Issue by thatdoorsajar** [laracasts/Integrated#85]
The fact that forms can only be submitted via submits defined through an `<input>` tag means the whole package has massive use limitations. I have multiple sites that I would like to use the Integrated package and Selenium on but my form submit buttons are defined via `<button>` tags so that I can easily incorporate FontAwesome (and other) icons. I will submit a pull request for this feature extension but wanted to check:
1. I havn't missed something glaringly obvious
2. If other people would find this useful

**Comment by JeffreyWay** [comment]
Yes - please submit a PR.

**Comment by alfredbez** [comment]
Looks like the [`selectButton` method](http://symfony.com/doc/current/components/dom_crawler.html#forms) should do the trick.

> A selectButton() method is available on the Crawler which returns another Crawler that matches a button (input[type=submit], input[type=image], or a **button**) with the given text.

However this method is already used [here](https://github.com/laracasts/Integrated/blob/master/src/Extensions/IntegrationTrait.php#L397)

**Comment by douglasz1** [comment]
I wanna do the other way around, use the input situation using Dusk lattest version of Laravel

**Comment by douglasz1** [comment]
`<input type="submit" id="asubmit" value="Enviar" tabindex="7" title="Clique para assinar o acompanhamento">
`
i want it to run a test what would be a laravel method for this situation?
