### ISSUE TITLE
AttachFile is failing

### ISSUE THREAD

**Issue by stevedotmt** [laracasts/Integrated#87]
I was trying to test a simple form where it takes an Image and a message. The form is build something like this.

```
{!! Form::open( ['action' => 'WelcomeController@store', 'files' => true] ) !!}

        <!-- image_url File input -->
        <div class="form-group">
            {!! Form::label('image_url', 'Upload an image:') !!}
            {!! Form::file('image_url')!!}
        </div>

        <!-- message From Input -->
        <div class="form-group">
            {!! Form::label('message', 'Enter the message:') !!}
            {!! Form::text('message', null, ['class' => 'form-control']) !!}
        </div>

        <!-- Submit Button -->
        <div class="form-group">
           {!! Form::submit('Create Profile', ['class' => 'btn btn-primary form-control']) !!}
        </div>

{!! Form::close() !!}
```

I wrote the following test using the Integrated Package.

```
public function testFileUpload()
    {
        $this->visit('profile/create')
            ->see('Profile')
            ->attachFile('image_url', 'C:\Users\Steve\Dropbox\Work\Laravel\integration\tests\test.jpg')
            ->type('Some Message', 'message')
            ->press('Create Profile')
            ->seePageIs('profile/store')
            ->see('Success');
    }
```

When i run the following test I get an exception from the move method.

`.PHP Fatal error:  Call to a member function move()`

Now my toughts are it is failing because of the validtion rules the `Symfony\Component\HttpFoundation\File\UplaodedFile` has inside of the move method.

It seems that it not only me that is having the same issues you can see more information from other people over here https://github.com/laracasts/Integrated/issues/20 

If you need any more information please ask.

**Comment by jildertmiedema** [comment]
I've created a PR for this, can you please test it?

https://github.com/laracasts/Integrated/pull/92

**Comment by stevedotmt** [comment]
I'll test it later today :) Thank you.

**Comment by jildertmiedema** [comment]
@SteveAzz thanks in advance. 

It works for me, so I hope it works for you too.

**Comment by stevedotmt** [comment]
Works like a charm, left a comment there as well :+1:

**Comment by JeffreyWay** [comment]
Fixed.
