### ISSUE TITLE
Access level of Emulator::see and IntegrationTrait::see don't match

### ISSUE THREAD

**Issue by HolgerW1** [laracasts/Integrated#89]
PHP versions prior to 5.5.25 didn't throw an error but 5.5.25 does (https://bugs.php.net/bug.php?id=69467)

Both methods need to have the same access level, either protected or public.

```
Fatal error: Access level to Laracasts\Integrated\Extensions\Traits\LaravelTestCase::see() must be public (as in class Laracasts\Integrated\Emulator) in /frontend/vendor/laracasts/integrated/src/Extensions/Laravel.php on line 12
```

Edit: of course not only the "see" method is affected but all methods of the Emulator interface.

**Comment by HolgerW1** [comment]
2ab96f0cee8d67a61e6b460a1ffd2b931aa71d77 in the master branch fixes the problem.
This should be tagged asap imho.

**Comment by olimorris** [comment]
@JeffreyWay - Can you tag this please. It's causing all sorts of funny business in CodeShip

**Comment by JeffreyWay** [comment]
Done.
