### ISSUE TITLE
Guzzle 6 (PSR-7) incompatible, (fabpot/goutte)

### ISSUE THREAD

**Issue by jildertmiedema** [laracasts/Integrated#93]
Are in the require part of `composer.json`

What about moving them to the suggest?

"fabpot/goutte": "~2.0",
"instaclick/php-webdriver": "~1.4"

I can't install Guzzle 6, because "fabpot/goutte" denies it, but i don't use "fabpot/goutte".

**Comment by sameerpanjwani** [comment]
+1 facing same issue

**Comment by vredeling** [comment]
+1 as part of Drupal 8 dev issue: https://www.drupal.org/node/2493911
Guzzle 6 + php5.5 compatibility is being discussed still but fabpot/goutte blocks upgrading to Guzzle 6 anyway.

**Comment by fabpot** [comment]
Goutte 3.0.0 with Guzzle 6.0 support is out.

**Comment by vredeling** [comment]
Awesome! Thanks
