### ISSUE TITLE
Params in GET and DELETE requests

### ISSUE THREAD

**Issue by fenos** [laracasts/Integrated#94]
Is not possible to attach params to GET and DELETE requests directly from the package API. I think they're really handy when testing specific filters when getting data.

Obviously is not a big deal when we need to pass data we can use directly the method `call()` as the `get()` method does.

It was nice if we can pass as second param an optional array with the data to send with the request. I can make a PR if you would like have it too :)

**Comment by moon0326** [comment]
There are two PRs that should take care of your issue.

https://github.com/laracasts/Integrated/pull/80
https://github.com/laracasts/Integrated/pull/67

**Comment by fenos** [comment]
Oh thanks, sorry i didn't look at it
